### ISSUE TITLE
wrong expression : jamTime << minJamTime

### ISSUE THREAD

**Issue by catx23** [davehakkens/shredder-reverse#3]
Are you sure about this ? 
See, https://github.com/davehakkens/shredder-reverse/blob/master/Arduino%20code.ino#L139

thanks btw. for adding the SVG but the real source files which output those would have been more practical.

**Comment by catx23** [comment]
there is another problem btw. your button reader code doesn't do [de-bouncing](https://github.com/thomasfredericks/Bounce2) which can get really dangerous and fatal. if you leave the code running for some hours, and worst : have high power equipment around you can see how it affects the signals.

**Comment by catx23** [comment]
the other problem which could be deadly is not using _unsigned long_ for timestamps. integers are limited and even the _unsigned long_ will roll over to negative after 49 days  :-) 

the more stable and reliable as I figured now after 3 days is to : 
1. don't use delays (ie: pure processing state machine)
2. test your code without serial statements, works differently then
3. use de-bouncers for all inputs

good luck

**Comment by alromh87** [comment]
Hello catx23, haven't seen you issue report before, but looks we where thinking about the same. 

I have just updated the code, so if you feel like giving it a try and let me know your toughs would be cool
