### ISSUE TITLE
License for the code & Documentation

### ISSUE THREAD

**Issue by darigovresearch** [davehakkens/shredder-reverse#5]
Could you please advise on what the license is for the code?

I am assuming that the documentation is a CC-BY-SA 4.0 like the starter kits but the code would be MIT like the community platform. Making it explicit in this repository makes it easier to get started.

Would like to try to continue & improve the code and documentation but without the license (hopefully an open source one) means that our improvements can't be used by the wider community.

Thanks for the whole project & taking a look at this issue!

**Comment by davehakkens** [comment]
You can just use whatever you need from it.
If you feel more comfortable with a license code, add a pull request and i'll add it.

**Comment by darigovresearch** [comment]
Sounds good, will add a pull request this weekend. 
Feel free to assign the issue to @darigovresearch and will handle the rest.

**Comment by darigovresearch** [comment]
Pull request has been made, feel free to make any modifications required or let us know if you need anything else before merging it

**Comment by darigovresearch** [comment]
Commit bf3dcbb closes the issue, thanks for merging the pull request!
